### ISSUE TITLE
boot.cfg changes not loading. 

### ISSUE THREAD

**Issue by gnogeek** [samdbmg/dhcp-netboot.xyz#6]
First thanks for you effort to make this work so fine,

I'm facing something that I don't know if call it really an issue,

I make modifications on the boot.cfg, but them are not reflected at all, its just keep getting the menus and the config from remote.

I would like to configure it to get local assets from my local vm.

Thanks in advance.

**Comment by zyssai** [comment]
Hi, I would just open an issue for the same problem.
Changes mades in boot.cfg (especially set win_base_url in my case) are not applied at boot.

`docker network create --driver=ipvlan --gateway=192.168.0.254 --subnet=192.168.0.2/24 --ip-range=192.168.0.100/32 -o parent=enp4s0 netbootxyz_network

version: "3.9"
networks:
  netbootxyz_network:
    external: true
services:
  netbootxyz:
    container_name: netbootxyz
    image: samdbmg/dhcp-netboot.xyz:latest
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - DHCP_RANGE_START=192.168.0.2
    restart: unless-stopped
    networks:
      netbootxyz_network:
        ipv4_address: 192.168.0.251
    ports:
      - 3000:3000
      - 69:69/udp
#      - 8080:80 #optional
    cap_add:
      - NET_ADMIN
    volumes:
      - $DOCKERDIR/netbootxyz:/etc/netbootxyz
      - $DOCKERDIR/netbootxyz/config:/config
      - $PXEDIR:/assets
`

**Comment by samdbmg** [comment]
Hi both, sorry for the slow response, it's been a busy few months in my personal life!

I think the change in #8 should have fixed this: it turns out the DHCP `next-server` wasn't being set properly so some fallback behaviour was triggered in netboot.xyz. If you get the chance, would you mind trying changing the config and local assets again and re-opening if it doesn't work for you?

**Comment by zyssai** [comment]
No problem we are all busy 😉
Will try it next week and let you know, thanks for your support!

**Comment by zyssai** [comment]
Hi!

Changes mades in boot.cfg or windows.ipxe for example are working!
I just need to disable Signature checks or I end with this screen:
![IMG_20220725_175007~2](https://user-images.githubusercontent.com/15921623/180824847-313ad556-30c3-4c8d-98b7-bae4a46f2704.jpg)

Is it ok to have all these errors at start?
![IMG_20220725_180444~2](https://user-images.githubusercontent.com/15921623/180824919-8f5c9078-a298-4950-a9a5-aed23504ce7c.jpg)

Thanks for your support!

**Comment by samdbmg** [comment]
> I just need to disable Signature checks or I end with this screen:
This is a [limitation of netboot.xyz](https://netboot.xyz/docs/faq/#does-netbootxyz-support-secure-boot): the binaries aren't signed to allow secure boot to work.

> Another thing, is it ok to have all these errors at start?
Yes, what's happening there is it's trying to find a specific set of vars and config for that computer, rather than the generic one, but of course there is no specific config in your environment, so it fails and falls back to generic. In a large enterprise environment there might be specific config on a netboot server for each computer, e.g. so you can just plug it in and power it on, and it'll install and set up itself. But in an homelab type environment, that's probably complexity you don't need.

I've opened https://github.com/samdbmg/dhcp-netboot.xyz/issues/10 to call those out in the README
